### PR TITLE
Removed distutils fallback

### PR DESCRIPTION
**Pull request by claudep**
As of https://github.com/kennethreitz/setup.py/blob/master/setup.py

### CODE REVIEW

**Comment by claudep** [comment]
Then you won't be able to install this package anyway as several of its dependencies are also directly importing setuptools.setup without fallback. I think the time caring for a missing setuptools package is over now.

**Comment by chfw** [comment]
Here's the reference to the issue: https://github.com/moremoban/pypi-mobans/issues/66.

The main concern is for embedded device and docker builds where size matters.

**Comment by claudep** [comment]
I see, however I'm afraid unless a PEP changes that, the current good practice is still to directly import setuptools.setup.
See https://docs.python.org/3/library/distutils.html which is some official endorsement of setuptools.

**Comment by chfw** [comment]
Thanks for further elaboration and we now understand both sides of the opinion. I have no objections for the merge.

**Comment by timofurrer** [comment]
Totally agree! Thanks 🎉

**Pull request merged**
