### PR TITLE
Replaced vendored openpyxl by a dependency

### PR DESCRIPTION
**Pull request by claudep**
Thanks Tommy Anthony for the initial patch.

### CODE REVIEW

**Comment by claudep** [comment]
WIP: update method for syncing `tablib.core.__version__` and `setup.py`'s setup version param.

**Comment by claudep** [comment]
Seems this is ready for review.

**Comment by kennethreitz** [comment]
@claudep can you open this again against the master branch? sorry, doing some repo cleanup.

**Comment by claudep** [comment]
Sure, but no need to close the pull request and create another one, I can rebase my patch and force-push it. Could you reopen?

**Comment by kennethreitz** [comment]
I deleted the `develop` branch, which this PR was made against. GitHub automatically closes the PR in that case, apparently. Sorry for the inconvenience, I didn't know :)

**Comment by claudep** [comment]
Yes, there was something strange with that develop branch. I opened #221, hopefully against the right branch!

**Pull request closed without merging**
