### PR TITLE
CSV custom delimiter support

### PR DESCRIPTION
**Pull request by papisz**
CSV and TSV are very similar formats. Some people need tab separated values, some (me) need `;`-separated values.
So I've come up with the idea of having one interface for all kinds of \*SV formats (delimited by any character you need).
The idea is to keep csv and tsv format in the Dataset class and also add functions `set_*` and `get_*` (e.g. `set_csv`, `get_csv`) which allow to use custom arguments (you can't do it with a property). In my case I've added `delimiter` argument.

There are also two testcases showing how to use it. Other tests also pass, so hopefully I haven't broken anything :-).

Please tell me what you think. Is this idea OK? As I said just need `;`-separated values support, but maybe someone else will need `:` or `^` or anything-else-separated values support in the future. Perhaps there is a better way to provide it, but I haven't figured out anything better.

### CODE REVIEW

**Comment by Summer88** [comment]
+1

**Comment by kellerkind** [comment]
+1

**Comment by SalahAdDin** [comment]
:+1:

**Comment by kennethreitz** [comment]
This looks useful! Would have to manually integrate now though, as the codebase has changed quite a bit since you made this contribution (sorry for the huge huge huge delay).

**Comment by kennethreitz** [comment]
:sparkles: :cake: :sparkles:

**Comment by kellerkind** [comment]
Thanks, works great!

	>>> open('test.csv', 'rb').read()
	'Name;Vorname;Stadt\nMustermann;Max;Hamburg\nNordlicht;Nanni;K\xc3\xb6ln\n'


	>>> d = tablib.import_set(open('test.csv').read(), format='csv',delimiter=';')
	>>> d.get_json()
	'[{"Name": "Mustermann", "Vorname": "Max", "Stadt": "Hamburg"}, {"Name": "Nordlicht", "Vorname": "Nanni", "Stadt": "K\\u00f6ln"}]'

**Pull request merged**
