### PR TITLE
Replaced vendored openpyxl by a dependency

### PR DESCRIPTION
**Pull request by claudep**
Re-opened #217 against master.

### CODE REVIEW

**Comment by franciscod** [comment]
Should we un-vendor every dependency? it's very weird in this way :) It seems this project is pre-`pip`

**Comment by claudep** [comment]
The aim (for me as a simple contributor) is to unvendor other dependencies too. I'm just segmenting the patch initiated by Tommy Anthony in #195, to fix issues separately.

**Comment by kennethreitz** [comment]
The intention behind the vendoring was for user simplicity. I didn't want users of Tablib to have to install a number of other dependencies in order to use the software. This was compounded by the fact that I had to port the codebases to Python 3 myself, and make other modifications. 

If all of this software is now properly maintained and packaged for both Python 2 and Python 3, un-vendoring is a possibility. The large number of sub-dependencies that this would pass on to the user is quite unfortunate, but it would also reduce maintenance burden (ideally).

**Comment by claudep** [comment]
That was certainly a good design when it was decided. I think now that Python dependency management has improved a lot during the recent years, and it *may* be time to switch to build on a dependency system again.

**Comment by kennethreitz** [comment]
Agreed, as long as everything now available for Python 3 (I haven't checked).

**Comment by claudep** [comment]
Travis should tell us that :-)

**Comment by kennethreitz** [comment]
Travis is broken (for this project) at the moment, unfortunately. I sent a message to their support a few days ago, but haven't heard anything yet. 

I may take the time to just switch this project over to my http://ci.kennethreitz.org/

**Comment by claudep** [comment]
There seems to be an issue with the develop branch. But for other branches like:
master: https://travis-ci.org/kennethreitz/tablib/builds/109605530
this PR: https://travis-ci.org/kennethreitz/tablib/builds/109668283
Results seem to be fine.

I think that at some time, your repo was setup with the develop branch as the main branch, instead of master. It might have been the source of various problems.

**Comment by kennethreitz** [comment]
Yes, I made some adjustments a few days ago. There is no longer a develop branch.

I am annoyed with Travis :)

**Comment by iurisilvio** [comment]
These are all tablib Python 3 vendored packages:

```
    'tablib.packages.xlwt3',
    'tablib.packages.xlrd3',
    'tablib.packages.odf3',
    'tablib.packages.openpyxl3',
    'tablib.packages.openpyxl3.shared',
    'tablib.packages.openpyxl3.reader',
    'tablib.packages.openpyxl3.writer',
    'tablib.packages.yaml3',
    'tablib.packages.dbfpy3'
```

These claim to support Python 3:

https://pypi.python.org/pypi/xlwt
https://pypi.python.org/pypi/xlrd
https://pypi.python.org/pypi/odfpy
https://pypi.python.org/pypi/openpyxl
https://pypi.python.org/pypi/PyYAML

The dbfpy is not clear about Python 3 support. It is a simple package, I guess they support, but used it only in Python 2.7.

**Comment by franciscod** [comment]
For dbf support, there's this on pypi that has many recent downloads: https://pypi.python.org/pypi/dbf

**Comment by iurisilvio** [comment]
Good. I don't know which package is the vendored one. Maybe it is this `dbf` instead of `dbfpy`.

**Comment by claudep** [comment]
I've just rebased the branch to check if tests are still happy. Is there anything blocking this?
I'm still available to continue the work for other dependencies after this one is merged.

**Comment by vToMy** [comment]
I would LOVE to have this merged.

**Comment by claudep** [comment]
I'll rebase my patch ASAP.

**Comment by claudep** [comment]
Rebase done.

**Comment by iurisilvio** [comment]
Merged.

It is part of #273 work.

**Comment by vToMy** [comment]
Wow, that was fast. Thanks guys :)

**Pull request merged**
