### PR TITLE
Import ascii characters not valid with unicode literals

### LINKED ISSUE #215: Import ascii characters not valid.
I tried to add data to the tablib Dataset. I use django import export to do so. Everything goes well with the data until it is in the dataset. Once it is added and I try to read the data I get the following error. 

```
UnicodeEncodeError encountred while trying to read file: 'ascii' codec can't encode character u'\xc6' in position 241: ordinal not in range(128)
```

It is about the text Ævar. This name will fail when you try to read the data from the Dataset.

### PR DESCRIPTION
**Pull request by browniebroke**
I had the same bug as #215 so I started working on a fix. It looks like it's a problem is around unicode literals.

- [x] Test case to reproduce the bug
- [x] Provide a patch

### CODE REVIEW

**Comment by Benny-** [comment]
@browniebroke hi, I wanted to apply this patch to my private tablib repo but I could not find your fork. Is your fork private?

**Comment by Benny-** [comment]
Found it! It was here: https://github.com/founders4schools/tablib

**Comment by timofurrer** [comment]
Could you please resolve the merge conflicts? Thanks 🎉

**Comment by browniebroke** [comment]
I don't have access to the base fork anymore, but I've resolved the conflicts in #350. Closing this one which I can no longer update.

**Pull request closed without merging**
